spring.application.name=user-serice
jwt.secretKey=gvgfutr56xr43w4zcr43x4345cvzhvhrcxry445z45czjvtvr54ewx3w5t7bi7vxmunku,i554xcr56e4xbgvn
server.port=9020

spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.jpa.hibernate.ddl-auto=update